
service: aws-task-manager

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
package:
  individually: true

functions:
  createTask:
    handler: src/handlers/createTask.createTaskHandler
    events:
      - http:
          path: tasks
          method: post
  getTask:
    handler: src/handlers/getTask.getTaskHandler
    events:
      - http:
          path: tasks/{id}
          method: get
  updateTask:
    handler: src/handlers/updateTask.updateTaskHandler
    events:
      - http:
          path: tasks/{id}
          method: put
  deleteTask:
    handler: src/handlers/deleteTask.deleteTaskHandler
    events:
      - http:
          path: tasks/{id}
          method: delete
  listTasks:
    handler: src/handlers/listTasks.listTasksHandler
    events:
      - http:
          path: tasks
          method: get

resources:
  Resources:
    TasksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Tasks2'
